obj-$(CONFIG_TEGRA_PCM) += tegra_pcm_rpc.o
obj-$(CONFIG_TEGRA_I2S) += tegra_i2s.o tegra_transport.o
obj-$(CONFIG_TEGRA_GENERIC_CODEC) += tegra_soc_audio.o
obj-$(CONFIG_TEGRA_GENERIC_CODEC) += tegra_codec_rpc.o