#ifndef STAR_PINMUX_DEFINITION_H
#define STAR_PINMUX_DEFINITION_H

#define BOARD_ID_FIRENZE		0x0B07
#define BOARD_SKU_FIRENZE_REV_B		0x00
#define BOARD_ID_STAR		0x0B06
#define BOARD_SKU_STAR_REV_A		0x00

#define AP20PERI_NOTUSED 0
#if defined(CONFIG_MACH_STAR_FIRENZE)

/* GPIO PIN LIST */
#define STAR_BT_HOST_WAKEUP			AP20_GPIO_PC7
#define STAR_MOTION_INT		 		AP20_GPIO_PI0
#define STAR_MICROSD_DET_N			AP20_GPIO_PI5
#define STAR_CAM_PMIC_EN			AP20_GPIO_PJ5
#define STAR_AUDIO_VDD_3V0			AP20_GPIO_PK3
#define STAR_AUDIO_VDD_1V2			AP20_GPIO_PK4
#define STAR_HDMI_LDO_EN			AP20_GPIO_PK5
#define STAR_HDMI_INT_N				AP20_GPIO_PN7
#define STAR_IFX_SPI_SRDY			AP20_GPIO_PO5
#define STAR_IFX_SPI_MRDY			AP20_GPIO_PO0 
#define STAR_WLAN_EN				AP20_GPIO_PQ3
#define STAR_BT_EN					AP20_GPIO_PQ4
#define STAR_BLDCDC_RESET			AP20_GPIO_PR3
#define STAR_COMPASS_RESET			AP20_GPIO_PR4
#define STAR_COMPASS_INT			AP20_GPIO_PR5
#define STAR_LED_DRIVER_EN_PROX   	AP20_GPIO_PR7
#define STAR_WLAN_HOST_WAKEUP		AP20_GPIO_PS0
#define STAR_FLASH_LED_EN          	AP20_GPIO_PT4
#define STAR_WLAN_WAKEUP			AP20_GPIO_PT7
#define STAR_INT_N_MUIC				AP20_GPIO_PU0
#define STAR_AP20_UART_SW			AP20_GPIO_PU1
#define STAR_IFX_UART_SW			AP20_GPIO_PU2
#define STAR_USIF1_SW				AP20_GPIO_PU3
#define STAR_VIBE_EN   				AP20_GPIO_PU5
#define STAR_XMM6160_RESET			AP20_GPIO_PV0
#define STAR_XMM6160_ONOFF			AP20_GPIO_PV1
#define STAR_POWER_KEY				AP20_GPIO_PV2
#define STAR_LCD_RESET_N			AP20_GPIO_PV7
#define STAR_LED_DRIVER_EN			AP20_GPIO_PW3
#define STAR_BT_WAKEUP				AP20_GPIO_PX4
#define STAR_TOUCH_INT		 		AP20_GPIO_PX6
#define STAR_HEADSET_SENSE			AP20_GPIO_PAA3


/* PIN MUX ARRAY POSITION */
#define STAR_WLAN_SDIO       		AP20PERINFO(AP20_SDIO1, NvOdmSdioPinMap_Config1)     
#define STAR_NOT_USED_SDIO   		AP20PERINFO(AP20_SDIO2, AP20PERI_NOTUSED) 
#define STAR_MICROSD_SDIO    		AP20PERINFO(AP20_SDIO3, NvOdmSdioPinMap_Config2) 
#define STAR_MMC_SDIO       		AP20PERINFO(AP20_SDIO4, NvOdmSdioPinMap_Config1) 

#define STAR_UART1_IPC_UART			AP20PERINFO(AP20_UART1, NvOdmUartPinMap_Config6)                  
#define STAR_DEBUG_MSG_UART			AP20PERINFO(AP20_UART2, NvOdmUartPinMap_Config2) 
#define STAR_BLUETOOTH_UART			AP20PERINFO(AP20_UART3, NvOdmUartPinMap_Config1) 
#define STAR_NOT_USED4_UART			AP20PERINFO(AP20_UART4, AP20PERI_NOTUSED) 
#define STAR_NOT_USED5_UART			AP20PERINFO(AP20_UART5, AP20PERI_NOTUSED)
                                                
#define STAR_IPC_SPI				AP20PERINFO(AP20_SPI1, NvOdmSpiPinMap_Config1)      
#define STAR_TOUCH_SPI				AP20PERINFO(AP20_SPI2, NvOdmSpiPinMap_Config4)  
#define STAR_LCD_SPI				AP20PERINFO(AP20_SPI3, NvOdmSpiPinMap_Config3)  
#define STAR_NOT_USED4_SPI			AP20PERINFO(AP20_SPI4, AP20PERI_NOTUSED)  
#define STAR_NOT_USED5_SPI			AP20PERINFO(AP20_SPI5, AP20PERI_NOTUSED)  
                                                
#define STAR_I2C_PMU				AP20PERINFO(AP20_I2C_PMU, NvOdmI2cPmuPinMap_Config1) 
#define STAR_HDMI					AP20PERINFO(AP20_HDMI, NvOdmHdmiPinMap_Config1) 

#define STAR_VIBRATOR_PWM			AP20PERINFO(AP20_PWM, NvOdmPwmPinMap_Config1) 
                                                
#define STAR_AUDIO1_DAP				AP20PERINFO(AP20_DAP1, NvOdmDapPinMap_Config1)
#define STAR_AUDIO2_DAP				AP20PERINFO(AP20_DAP2, NvOdmDapPinMap_Config1) 
#define STAR_IPC_DAP				AP20PERINFO(AP20_DAP3, NvOdmDapPinMap_Config1)  
#define STAR_BT_DAP					AP20PERINFO(AP20_DAP4, NvOdmDapPinMap_Config1) 
#define STAR_FM_DAP					AP20PERINFO(AP20_DAP5, NvOdmDapPinMap_Config1) 
                                                
#define STAR_AUDIO_MCLK_EXT_CLOCK	AP20PERINFO(AP20_EXT_CLOCK1, NvOdmExternalClockPinMap_Config1)
#define STAR_AUDIO_MCLK2_EXT_CLOCK	AP20PERINFO(AP20_EXT_CLOCK2, NvOdmExternalClockPinMap_Config1)
#define STAR_CAM_MCLK_EXT_CLOCK		AP20PERINFO(AP20_EXT_CLOCK3, NvOdmExternalClockPinMap_Config1)
#define STAR_VT_VI					AP20PERINFO(AP20_VIDEO_INPUT, NvOdmVideoInputPinMap_Config2)
#define STAR_LCD_DISPLAY			AP20PERINFO(AP20_DISPLAY1, NvOdmDisplayPinMap_Config1)
#define STAR_NOT_USED_DISPLAY		AP20PERINFO(AP20_DISPLAY2, AP20PERI_NOTUSED)
#define STAR_KEY_KBD				AP20PERINFO(AP20_KBD, NvOdmKbdPinMap_Config4)
#define STAR_TV_OUT_TVO				AP20PERINFO(AP20_TVO, NvOdmTvoPinMap_Config1) 
#define STAR_NOT_USED1_BKL_PWM		AP20PERINFO(AP20_BKL_PWM1, AP20PERI_NOTUSED)
#define STAR_NOT_USED2_BKL_PWM		AP20PERINFO(AP20_BKL_PWM2, AP20PERI_NOTUSED) 
#define STAR_NOT_USED3_BKL_PWM		AP20PERINFO(AP20_BKL_PWM3, AP20PERI_NOTUSED) 
#define STAR_NOT_USED4_BKL_PWM		AP20PERINFO(AP20_BKL_PWM4, AP20PERI_NOTUSED) 
#define STAR_NOT_USED_TWC			AP20PERINFO(AP20_TWC, AP20PERI_NOTUSED) 
#define STAR_NOT_USED_ULPI			AP20PERINFO(AP20_ULPI, AP20PERI_NOTUSED)
#define STAR_NOT_USED_SPDIF			AP20PERINFO(AP20_SPDIF, AP20PERI_NOTUSED)
#define STAR_NOT_USED_HSI			AP20PERINFO(AP20_HSI, AP20PERI_NOTUSED) 
#define STAR_NOT_USED_ATA			AP20PERINFO(AP20_ATA, AP20PERI_NOTUSED) 
#define STAR_NOT_USED_NAND			AP20PERINFO(AP20_NAND, AP20PERI_NOTUSED) 
#define STAR_NOT_USED_HDCP			AP20PERINFO(AP20_HDCP, AP20PERI_NOTUSED)
#define STAR_NOT_USED_SYNC_NOR		AP20PERINFO(AP20_SYNC_NOR, AP20PERI_NOTUSED)
#define STAR_NOT_USED_MIO			AP20PERINFO(AP20_MIO, AP20PERI_NOTUSED)
#define STAR_NOT_USED1_CRT			AP20PERINFO(AP20_CRT1, AP20PERI_NOTUSED) 
#define STAR_NOT_USED2_CRT         	AP20PERINFO(AP20_CRT2, AP20PERI_NOTUSED)
#define STAR_NOT_USED_ONEWIRE		AP20PERINFO(AP20_ONEWIRE, AP20PERI_NOTUSED) 
#define STAR_NOT_USED_PCI_EXP		AP20PERINFO(AP20_PCI_EXP, AP20PERI_NOTUSED) 
#define STAR_NOT_USED_PTM			AP20PERINFO(AP20_PTM, AP20PERI_NOTUSED) 

/* POWER INDEX SETTING */
#define STAR_NVVDD_SV1_1V0       	Max8907bPmuSupply_LX_V1
#define STAR_NVVDD_SV2_1V2       	Max8907bPmuSupply_LX_V2
#define STAR_NVVDD_SV3_1V8       	Max8907bPmuSupply_LX_V3
#define STAR_NVVDD_LDO1_3V3      	Max8907bPmuSupply_LDO1
#define STAR_NVVDD_LDO2_1V1      	Max8907bPmuSupply_LDO2
#define STAR_NVVDD_LDO3_1V8      	Max8907bPmuSupply_LDO3
#define STAR_NVVDD_LDO4_3V3      	Max8907bPmuSupply_LDO4
#define STAR_NVVDD_LDO5_2V8      	Max8907bPmuSupply_LDO5
#define STAR_NVVDD_LDO6_1V8      	Max8907bPmuSupply_LDO6
#define STAR_SENNS_VDD_3V0       	Max8907bPmuSupply_LDO7
#define STAR_VDD_FUSE_3V3        	Max8907bPmuSupply_LDO8
#define STAR_NVVDD_LDO9_1V8      	Max8907bPmuSupply_LDO9
#define STAR_TOUCH_3V3          	Max8907bPmuSupply_LDO10
#define STAR_NVVDD_LDO11_3V3     	Max8907bPmuSupply_LDO11
#define STAR_LDO12_SD_3V0        	Max8907bPmuSupply_LDO12
#define STAR_NVVDD_LDO13_2V8     	Max8907bPmuSupply_LDO13
#define STAR_NVVDD_LDO14_2V8     	Max8907bPmuSupply_LDO14
#define STAR_NVVDD_LDO15_3V3     	Max8907bPmuSupply_LDO15
#define STAR_MOTOR_3V0          	Max8907bPmuSupply_LDO16
#define STAR_NVVDD_LDO17_1V2     	Max8907bPmuSupply_LDO17
#define STAR_NVVDD_LDO18_1V8     	Max8907bPmuSupply_LDO18
#define STAR_NVVDD_LDO19_2V8     	Max8907bPmuSupply_LDO19
#define STAR_NVVDD_LDO20_0V     	Max8907bPmuSupply_LDO20
#elif defined(CONFIG_MACH_STAR_REV_A)
/* GPIO PIN LIST */
#define STAR_BT_HOST_WAKEUP			AP20_GPIO_PC7
#define STAR_MOTION_INT		 		AP20_GPIO_PI0
#define STAR_HEADSET_SENSE			AP20_GPIO_PI2
#define STAR_MICROSD_DET_N			AP20_GPIO_PI5
#define STAR_GPS_RESET_N			AP20_GPIO_PJ0
#define STAR_GPS_PWR_ON				AP20_GPIO_PJ1
#define STAR_CAM_PMIC_EN			AP20_GPIO_PJ5  // 확인요
#define STAR_AUDIO_VDD_3V0			AP20_GPIO_PK3
//#define STAR_AUDIO_VDD_1V2			AP20_GPIO_PK4 // 삭제
#define STAR_HDMI_LDO_EN			AP20_GPIO_PK5
#define STAR_HDMI_INT_N				AP20_GPIO_PN7
#define STAR_IFX_SPI_SRDY			AP20_GPIO_PO5
#define STAR_IFX_SPI_MRDY			AP20_GPIO_PO0 
#define STAR_WLAN_EN				AP20_GPIO_PQ3
#define STAR_BT_EN					AP20_GPIO_PQ4
#define STAR_BLDCDC_RESET			AP20_GPIO_PR3
//#define STAR_COMPASS_RESET			AP20_GPIO_PR4 // 삭제
#define STAR_COMPASS_INT			AP20_GPIO_PR4
#define STAR_LED_DRIVER_EN_PROX   	AP20_GPIO_PR7
#define STAR_WLAN_HOST_WAKEUP		AP20_GPIO_PS0
#define STAR_CHG_EN_SET_N_AP20		AP20_GPIO_PS1
#define STAR_STATUS_SET_N_AP20		AP20_GPIO_PS2
#define STAR_WLAN_WAKEUP			AP20_GPIO_PG2
#define STAR_INT_N_MUIC				AP20_GPIO_PU0
#define STAR_AP20_UART_SW			AP20_GPIO_PU1
#define STAR_IFX_UART_SW			AP20_GPIO_PU2
#define STAR_USIF1_SW				AP20_GPIO_PU3
#define STAR_VIBE_EN   				AP20_GPIO_PU5
#define STAR_VIBE_PWM  				AP20_GPIO_PU6
#define STAR_XMM6160_RESET			AP20_GPIO_PV0
#define STAR_XMM6160_ONOFF			AP20_GPIO_PV1
#define STAR_POWER_KEY				AP20_GPIO_PV2
#define STAR_LCD_RESET_N			AP20_GPIO_PV7
//#define STAR_LED_DRIVER_EN			AP20_GPIO_PW3 // 삭제
#define STAR_BT_WAKEUP				AP20_GPIO_PX4
#define STAR_TOUCH_MAKER_ID		 	AP20_GPIO_PX5
#define STAR_TOUCH_INT		 		AP20_GPIO_PX6
#define STAR_BATT_LOW_INT			AP20_GPIO_PW3
#define STAR_FLASH_LED_EN          	AP20_GPIO_PBB4


/* PIN MUX ARRAY POSITION */
#define STAR_WLAN_SDIO       		AP20PERINFO(AP20_SDIO1, NvOdmSdioPinMap_Config1)     
#define STAR_NOT_USED_SDIO   		AP20PERINFO(AP20_SDIO2, AP20PERI_NOTUSED) 
#define STAR_MICROSD_SDIO    		AP20PERINFO(AP20_SDIO3, NvOdmSdioPinMap_Config2) 
#define STAR_MMC_SDIO       		AP20PERINFO(AP20_SDIO4, NvOdmSdioPinMap_Config2) 

#define STAR_UART1_IPC_UART			AP20PERINFO(AP20_UART1, NvOdmUartPinMap_Config6)                  
#define STAR_DEBUG_MSG_UART			AP20PERINFO(AP20_UART2, NvOdmUartPinMap_Config2) 
#define STAR_BLUETOOTH_UART			AP20PERINFO(AP20_UART3, NvOdmUartPinMap_Config1) 
#define STAR_GPS_UART				AP20PERINFO(AP20_UART4, NvOdmUartPinMap_Config2)
#define STAR_NOT_USED5_UART			AP20PERINFO(AP20_UART5, AP20PERI_NOTUSED)
                                                
#define STAR_IPC_SPI				AP20PERINFO(AP20_SPI1, NvOdmSpiPinMap_Config1)
#define STAR_NOT_USED2_SPI			AP20PERINFO(AP20_SPI2, AP20PERI_NOTUSED)       
#define STAR_NOT_USED3_SPI			AP20PERINFO(AP20_SPI3, AP20PERI_NOTUSED)  
#define STAR_NOT_USED4_SPI			AP20PERINFO(AP20_SPI4, AP20PERI_NOTUSED)  
#define STAR_NOT_USED5_SPI			AP20PERINFO(AP20_SPI5, AP20PERI_NOTUSED)  
                                                
#define STAR_I2C_PMU				AP20PERINFO(AP20_I2C_PMU, NvOdmI2cPmuPinMap_Config1) 
#define STAR_HDMI					AP20PERINFO(AP20_HDMI, NvOdmHdmiPinMap_Config1) 

#define STAR_VIBRATOR_PWM			AP20PERINFO(AP20_PWM, NvOdmPwmPinMap_Config1) 
                                                
#define STAR_AUDIO1_DAP				AP20PERINFO(AP20_DAP1, NvOdmDapPinMap_Config1)
#define STAR_AUDIO2_DAP				AP20PERINFO(AP20_DAP2, NvOdmDapPinMap_Config1) 
#define STAR_IPC_DAP				AP20PERINFO(AP20_DAP3, NvOdmDapPinMap_Config1)  
#define STAR_BT_DAP					AP20PERINFO(AP20_DAP4, NvOdmDapPinMap_Config1) 
#define STAR_FM_DAP					AP20PERINFO(AP20_DAP5, NvOdmDapPinMap_Config1) 
                                                
#define STAR_AUDIO_MCLK_EXT_CLOCK	AP20PERINFO(AP20_EXT_CLOCK1, NvOdmExternalClockPinMap_Config1)
#define STAR_AUDIO_MCLK2_EXT_CLOCK	AP20PERINFO(AP20_EXT_CLOCK2, NvOdmExternalClockPinMap_Config1)
#define STAR_CAM_MCLK_EXT_CLOCK		AP20PERINFO(AP20_EXT_CLOCK3, NvOdmExternalClockPinMap_Config1)
#define STAR_VT_VI					AP20PERINFO(AP20_VIDEO_INPUT, NvOdmVideoInputPinMap_Config2)
#define STAR_LCD_DISPLAY			AP20PERINFO(AP20_DISPLAY1, NvOdmDisplayPinMap_Config1)
#define STAR_NOT_USED_DISPLAY		AP20PERINFO(AP20_DISPLAY2, AP20PERI_NOTUSED)
#define STAR_KEY_KBD				AP20PERINFO(AP20_KBD, AP20PERI_NOTUSED)
#define STAR_TV_OUT_TVO				AP20PERINFO(AP20_TVO, NvOdmTvoPinMap_Config1) 
#define STAR_NOT_USED1_BKL_PWM		AP20PERINFO(AP20_BKL_PWM1, AP20PERI_NOTUSED)
#define STAR_NOT_USED2_BKL_PWM		AP20PERINFO(AP20_BKL_PWM2, AP20PERI_NOTUSED) 
#define STAR_NOT_USED3_BKL_PWM		AP20PERINFO(AP20_BKL_PWM3, AP20PERI_NOTUSED) 
#define STAR_NOT_USED4_BKL_PWM		AP20PERINFO(AP20_BKL_PWM4, AP20PERI_NOTUSED) 
#define STAR_NOT_USED_TWC			AP20PERINFO(AP20_TWC, AP20PERI_NOTUSED) 
#define STAR_NOT_USED_ULPI			AP20PERINFO(AP20_ULPI, AP20PERI_NOTUSED)
#define STAR_NOT_USED_SPDIF			AP20PERINFO(AP20_SPDIF, AP20PERI_NOTUSED)
#define STAR_NOT_USED_HSI			AP20PERINFO(AP20_HSI, AP20PERI_NOTUSED) 
#define STAR_NOT_USED_ATA			AP20PERINFO(AP20_ATA, AP20PERI_NOTUSED) 
#define STAR_NOT_USED_NAND			AP20PERINFO(AP20_NAND, AP20PERI_NOTUSED) 
#define STAR_NOT_USED_HDCP			AP20PERINFO(AP20_HDCP, AP20PERI_NOTUSED)
#define STAR_NOT_USED_SYNC_NOR		AP20PERINFO(AP20_SYNC_NOR, AP20PERI_NOTUSED)
#define STAR_NOT_USED_MIO			AP20PERINFO(AP20_MIO, AP20PERI_NOTUSED)
#define STAR_NOT_USED1_CRT			AP20PERINFO(AP20_CRT1, AP20PERI_NOTUSED) 
#define STAR_NOT_USED2_CRT         	AP20PERINFO(AP20_CRT2, AP20PERI_NOTUSED)
#define STAR_NOT_USED_ONEWIRE		AP20PERINFO(AP20_ONEWIRE, AP20PERI_NOTUSED) 
#define STAR_NOT_USED_PCI_EXP		AP20PERINFO(AP20_PCI_EXP, AP20PERI_NOTUSED) 
#define STAR_NOT_USED_PTM			AP20PERINFO(AP20_PTM, AP20PERI_NOTUSED) 

/* POWER INDEX SETTING */
#define VCC_CPU_1V0                 Max8907bPmuSupply_LX_V1
#define VCC_CORE_1V2                Max8907bPmuSupply_LX_V2
#define VCC_IO_1V8                  Max8907bPmuSupply_LX_V3
#define VCC_DDRx_3V3                Max8907bPmuSupply_LDO1
#define VCC_PLL_1V1                 Max8907bPmuSupply_LDO2
#define VCC_LDO3_0V                 Max8907bPmuSupply_LDO3
#define VCC_USB_3V3                 Max8907bPmuSupply_LDO4
#define VCC_eMMC_2V8_150mA          Max8907bPmuSupply_LDO5
#define VCC_HDMI_PLL_1V8            Max8907bPmuSupply_LDO6
#define VCC_SENSOR_3V0              Max8907bPmuSupply_LDO7
#define VCC_SENSOR_1V8              Max8907bPmuSupply_LDO8
#define VCC_FUSE_3V3                Max8907bPmuSupply_LDO9
#define VCC_TOUCH_3V1               Max8907bPmuSupply_LDO10
#define VCC_HDMI_3V3                Max8907bPmuSupply_LDO11
#define VCC_SDIO_3V0                Max8907bPmuSupply_LDO12
#define VCC_MOTOR_3V0               Max8907bPmuSupply_LDO13
#define VCC_GPS_2V8                 Max8907bPmuSupply_LDO14
#define VCC_APTEMP_3V3              Max8907bPmuSupply_LDO15
#define VCC_eMMC_2V8_300mA          Max8907bPmuSupply_LDO16
#define VCC_MIPI_1V2                Max8907bPmuSupply_LDO17
#define VCC_VI_1V8                  Max8907bPmuSupply_LDO18
#define VCC_LDO19_0V                Max8907bPmuSupply_LDO19
#define VCC_LDO20_0V                Max8907bPmuSupply_LDO20
#elif defined(CONFIG_MACH_STAR_REV_B)
/* GPIO PIN LIST */
#define STAR_BT_HOST_WAKEUP			AP20_GPIO_PC7
#define STAR_MOTION_INT		 		AP20_GPIO_PI0
#define STAR_HEADSET_SENSE			AP20_GPIO_PI2
#define STAR_MICROSD_DET_N			AP20_GPIO_PI5
#define STAR_GPS_RESET_N			AP20_GPIO_PJ0
#define STAR_GPS_PWR_ON				AP20_GPIO_PJ1
#define STAR_CAM_PMIC_EN			AP20_GPIO_PJ5  // 확인요
#define STAR_AUDIO_VDD_3V0			AP20_GPIO_PK3
//#define STAR_AUDIO_VDD_1V2			AP20_GPIO_PK4 // 삭제
#define STAR_HDMI_LDO_EN			AP20_GPIO_PK5
#define STAR_HDMI_INT_N				AP20_GPIO_PN7
#define STAR_IFX_SPI_SRDY			AP20_GPIO_PO5
#define STAR_IFX_SPI_MRDY			AP20_GPIO_PO0 
#define STAR_WLAN_EN				AP20_GPIO_PQ3
#define STAR_BT_EN					AP20_GPIO_PQ4
#define STAR_BLDCDC_RESET			AP20_GPIO_PR3
//#define STAR_COMPASS_RESET			AP20_GPIO_PR4 // 삭제
#define STAR_COMPASS_INT			AP20_GPIO_PR4
#define STAR_LED_DRIVER_EN_PROX   	AP20_GPIO_PR7
#define STAR_WLAN_HOST_WAKEUP		AP20_GPIO_PS0
#define STAR_CHG_EN_SET_N_AP20		AP20_GPIO_PS1
#define STAR_STATUS_SET_N_AP20		AP20_GPIO_PS2
#define STAR_WLAN_WAKEUP			AP20_GPIO_PG2
#define STAR_INT_N_MUIC				AP20_GPIO_PU0
#define STAR_AP20_UART_SW			AP20_GPIO_PU1
#define STAR_IFX_UART_SW			AP20_GPIO_PU2
#define STAR_USIF1_SW				AP20_GPIO_PU3
#define STAR_VIBE_EN   				AP20_GPIO_PU5
#define STAR_VIBE_PWM  				AP20_GPIO_PU6
#define STAR_XMM6160_RESET			AP20_GPIO_PV0
#define STAR_XMM6160_ONOFF			AP20_GPIO_PV1
#define STAR_POWER_KEY				AP20_GPIO_PV2
#define STAR_LCD_RESET_N			AP20_GPIO_PV7
//#define STAR_LED_DRIVER_EN			AP20_GPIO_PW3 // 삭제
#define STAR_BT_WAKEUP				AP20_GPIO_PX4
#define STAR_TOUCH_MAKER_ID		 	AP20_GPIO_PX5
#define STAR_TOUCH_INT		 		AP20_GPIO_PX6
#define STAR_BATT_LOW_INT			AP20_GPIO_PW3
#define STAR_FLASH_LED_EN          	AP20_GPIO_PBB4


/* PIN MUX ARRAY POSITION */
#define STAR_WLAN_SDIO       		AP20PERINFO(AP20_SDIO1, NvOdmSdioPinMap_Config1)     
#define STAR_NOT_USED_SDIO   		AP20PERINFO(AP20_SDIO2, AP20PERI_NOTUSED) 
#define STAR_MICROSD_SDIO    		AP20PERINFO(AP20_SDIO3, NvOdmSdioPinMap_Config2) 
#define STAR_MMC_SDIO       		AP20PERINFO(AP20_SDIO4, NvOdmSdioPinMap_Config2) 

#define STAR_UART1_IPC_UART			AP20PERINFO(AP20_UART1, NvOdmUartPinMap_Config6)                  
#define STAR_DEBUG_MSG_UART			AP20PERINFO(AP20_UART2, NvOdmUartPinMap_Config2) 
#define STAR_BLUETOOTH_UART			AP20PERINFO(AP20_UART3, NvOdmUartPinMap_Config1) 
#define STAR_GPS_UART				AP20PERINFO(AP20_UART4, NvOdmUartPinMap_Config2)
#define STAR_NOT_USED5_UART			AP20PERINFO(AP20_UART5, AP20PERI_NOTUSED)
                                                
#define STAR_IPC_SPI				AP20PERINFO(AP20_SPI1, NvOdmSpiPinMap_Config1)
#define STAR_NOT_USED2_SPI			AP20PERINFO(AP20_SPI2, AP20PERI_NOTUSED)       
#define STAR_NOT_USED3_SPI			AP20PERINFO(AP20_SPI3, AP20PERI_NOTUSED)  
#define STAR_NOT_USED4_SPI			AP20PERINFO(AP20_SPI4, AP20PERI_NOTUSED)  
#define STAR_NOT_USED5_SPI			AP20PERINFO(AP20_SPI5, AP20PERI_NOTUSED)  
                                                
#define STAR_I2C_PMU				AP20PERINFO(AP20_I2C_PMU, NvOdmI2cPmuPinMap_Config1) 
#define STAR_HDMI					AP20PERINFO(AP20_HDMI, NvOdmHdmiPinMap_Config1) 

#define STAR_VIBRATOR_PWM			AP20PERINFO(AP20_PWM, NvOdmPwmPinMap_Config1) 
                                                
#define STAR_AUDIO1_DAP				AP20PERINFO(AP20_DAP1, NvOdmDapPinMap_Config1)
#define STAR_AUDIO2_DAP				AP20PERINFO(AP20_DAP2, NvOdmDapPinMap_Config1) 
#define STAR_IPC_DAP				AP20PERINFO(AP20_DAP3, NvOdmDapPinMap_Config1)  
#define STAR_BT_DAP					AP20PERINFO(AP20_DAP4, NvOdmDapPinMap_Config1) 
#define STAR_FM_DAP					AP20PERINFO(AP20_DAP5, NvOdmDapPinMap_Config1) 
                                                
#define STAR_AUDIO_MCLK_EXT_CLOCK	AP20PERINFO(AP20_EXT_CLOCK1, NvOdmExternalClockPinMap_Config1)
#define STAR_AUDIO_MCLK2_EXT_CLOCK	AP20PERINFO(AP20_EXT_CLOCK2, NvOdmExternalClockPinMap_Config1)
#define STAR_CAM_MCLK_EXT_CLOCK		AP20PERINFO(AP20_EXT_CLOCK3, NvOdmExternalClockPinMap_Config1)
#define STAR_VT_VI					AP20PERINFO(AP20_VIDEO_INPUT, NvOdmVideoInputPinMap_Config2)
#define STAR_LCD_DISPLAY			AP20PERINFO(AP20_DISPLAY1, NvOdmDisplayPinMap_Config1)
#define STAR_NOT_USED_DISPLAY		AP20PERINFO(AP20_DISPLAY2, AP20PERI_NOTUSED)
#define STAR_KEY_KBD				AP20PERINFO(AP20_KBD, AP20PERI_NOTUSED)
#define STAR_TV_OUT_TVO				AP20PERINFO(AP20_TVO, NvOdmTvoPinMap_Config1) 
#define STAR_NOT_USED1_BKL_PWM		AP20PERINFO(AP20_BKL_PWM1, AP20PERI_NOTUSED)
#define STAR_NOT_USED2_BKL_PWM		AP20PERINFO(AP20_BKL_PWM2, AP20PERI_NOTUSED) 
#define STAR_NOT_USED3_BKL_PWM		AP20PERINFO(AP20_BKL_PWM3, AP20PERI_NOTUSED) 
#define STAR_NOT_USED4_BKL_PWM		AP20PERINFO(AP20_BKL_PWM4, AP20PERI_NOTUSED) 
#define STAR_NOT_USED_TWC			AP20PERINFO(AP20_TWC, AP20PERI_NOTUSED) 
#define STAR_NOT_USED_ULPI			AP20PERINFO(AP20_ULPI, AP20PERI_NOTUSED)
#define STAR_NOT_USED_SPDIF			AP20PERINFO(AP20_SPDIF, AP20PERI_NOTUSED)
#define STAR_NOT_USED_HSI			AP20PERINFO(AP20_HSI, AP20PERI_NOTUSED) 
#define STAR_NOT_USED_ATA			AP20PERINFO(AP20_ATA, AP20PERI_NOTUSED) 
#define STAR_NOT_USED_NAND			AP20PERINFO(AP20_NAND, AP20PERI_NOTUSED) 
#define STAR_NOT_USED_HDCP			AP20PERINFO(AP20_HDCP, AP20PERI_NOTUSED)
#define STAR_NOT_USED_SYNC_NOR		AP20PERINFO(AP20_SYNC_NOR, AP20PERI_NOTUSED)
#define STAR_NOT_USED_MIO			AP20PERINFO(AP20_MIO, AP20PERI_NOTUSED)
#define STAR_NOT_USED1_CRT			AP20PERINFO(AP20_CRT1, AP20PERI_NOTUSED) 
#define STAR_NOT_USED2_CRT         	AP20PERINFO(AP20_CRT2, AP20PERI_NOTUSED)
#define STAR_NOT_USED_ONEWIRE		AP20PERINFO(AP20_ONEWIRE, AP20PERI_NOTUSED) 
#define STAR_NOT_USED_PCI_EXP		AP20PERINFO(AP20_PCI_EXP, AP20PERI_NOTUSED) 
#define STAR_NOT_USED_PTM			AP20PERINFO(AP20_PTM, AP20PERI_NOTUSED) 

/* POWER INDEX SETTING */
#define VCC_CPU_1V0                 Max8907bPmuSupply_LX_V1
#define VCC_CORE_1V2                Max8907bPmuSupply_LX_V2
#define VCC_IO_1V8                  Max8907bPmuSupply_LX_V3
#define VCC_DDRx_3V3                Max8907bPmuSupply_LDO1
#define VCC_PLL_1V1                 Max8907bPmuSupply_LDO2
#define VCC_LDO3_0V                 Max8907bPmuSupply_LDO3
#define VCC_USB_3V3                 Max8907bPmuSupply_LDO4
#define VCC_eMMC_2V8_150mA          Max8907bPmuSupply_LDO5
#define VCC_HDMI_PLL_1V8            Max8907bPmuSupply_LDO6
#define VCC_SENSOR_3V0              Max8907bPmuSupply_LDO7
#define VCC_SENSOR_1V8              Max8907bPmuSupply_LDO8
#define VCC_FUSE_3V3                Max8907bPmuSupply_LDO9
#define VCC_TOUCH_3V1               Max8907bPmuSupply_LDO10
#define VCC_HDMI_3V3                Max8907bPmuSupply_LDO11
#define VCC_SDIO_3V0                Max8907bPmuSupply_LDO12
#define VCC_MOTOR_3V0               Max8907bPmuSupply_LDO13
#define VCC_GPS_2V8                 Max8907bPmuSupply_LDO14
#define VCC_APTEMP_3V3              Max8907bPmuSupply_LDO15
#define VCC_eMMC_2V8_300mA          Max8907bPmuSupply_LDO16
#define VCC_MIPI_1V2                Max8907bPmuSupply_LDO17
#define VCC_VI_1V8                  Max8907bPmuSupply_LDO18
#define VCC_LDO19_0V                Max8907bPmuSupply_LDO19
#define VCC_LDO20_0V                Max8907bPmuSupply_LDO20
#elif defined(CONFIG_MACH_STAR_REV_C) || defined(CONFIG_MACH_STAR_REV_D) || defined(CONFIG_MACH_STAR_REV_E) || defined(CONFIG_MACH_STAR_REV_F)
/* GPIO PIN LIST */
#define STAR_BT_HOST_WAKEUP			AP20_GPIO_PC7
#define STAR_MOTION_INT		 		AP20_GPIO_PI0
#define STAR_HEADSET_SENSE			AP20_GPIO_PI2
#define STAR_MICROSD_DET_N			AP20_GPIO_PI5
#define STAR_GPS_RESET_N			AP20_GPIO_PJ0
#define STAR_GPS_PWR_ON				AP20_GPIO_PJ1
#define STAR_CAM_PMIC_EN			AP20_GPIO_PJ5  // 확인요
#define STAR_AUDIO_VDD_3V0			AP20_GPIO_PK3
//#define STAR_AUDIO_VDD_1V2			AP20_GPIO_PK4 // 삭제
#define STAR_HDMI_LDO_EN			AP20_GPIO_PK5
#define STAR_HDMI_INT_N				AP20_GPIO_PN7
#define STAR_IFX_SPI_SRDY			AP20_GPIO_PO5
#define STAR_IFX_SPI_MRDY			AP20_GPIO_PO0 
#define STAR_WLAN_EN				AP20_GPIO_PQ3
#define STAR_BT_EN					AP20_GPIO_PQ4
#define STAR_BLDCDC_RESET			AP20_GPIO_PR3
//#define STAR_COMPASS_RESET			AP20_GPIO_PR4 // 삭제
#define STAR_COMPASS_INT			AP20_GPIO_PR4
#define STAR_LED_DRIVER_EN_PROX   	AP20_GPIO_PR7
#define STAR_WLAN_HOST_WAKEUP		AP20_GPIO_PS0
#define STAR_CHG_EN_SET_N_AP20		AP20_GPIO_PS1
#define STAR_STATUS_SET_N_AP20		AP20_GPIO_PS2
#define STAR_WLAN_WAKEUP			AP20_GPIO_PG2
#define STAR_INT_N_MUIC				AP20_GPIO_PU0
#define STAR_AP20_UART_SW			AP20_GPIO_PU1
#define STAR_IFX_UART_SW			AP20_GPIO_PU2
#define STAR_USIF1_SW				AP20_GPIO_PU3
#define STAR_VIBE_EN   				AP20_GPIO_PU5
#define STAR_VIBE_PWM  				AP20_GPIO_PU6
#define STAR_XMM6160_RESET			AP20_GPIO_PV0
#define STAR_XMM6160_ONOFF			AP20_GPIO_PV1
#define STAR_POWER_KEY				AP20_GPIO_PV2
#define STAR_LCD_RESET_N			AP20_GPIO_PV7
//#define STAR_LED_DRIVER_EN			AP20_GPIO_PW3 // 삭제
#define STAR_BT_WAKEUP				AP20_GPIO_PX4
#define STAR_TOUCH_MAKER_ID		 	AP20_GPIO_PX5
#define STAR_TOUCH_INT		 		AP20_GPIO_PX6
#define STAR_BATT_LOW_INT			AP20_GPIO_PW3
#define STAR_FLASH_LED_EN          	AP20_GPIO_PBB4


/* PIN MUX ARRAY POSITION */
#define STAR_WLAN_SDIO       		AP20PERINFO(AP20_SDIO1, NvOdmSdioPinMap_Config1)     
#define STAR_NOT_USED_SDIO   		AP20PERINFO(AP20_SDIO2, AP20PERI_NOTUSED) 
#define STAR_MICROSD_SDIO    		AP20PERINFO(AP20_SDIO3, NvOdmSdioPinMap_Config2) 
#define STAR_MMC_SDIO       		AP20PERINFO(AP20_SDIO4, NvOdmSdioPinMap_Config2) 

#define STAR_UART1_IPC_UART			AP20PERINFO(AP20_UART1, NvOdmUartPinMap_Config6)                  
#define STAR_DEBUG_MSG_UART			AP20PERINFO(AP20_UART2, NvOdmUartPinMap_Config2) 
#define STAR_BLUETOOTH_UART			AP20PERINFO(AP20_UART3, NvOdmUartPinMap_Config1) 
#define STAR_GPS_UART				AP20PERINFO(AP20_UART4, NvOdmUartPinMap_Config2)
#define STAR_NOT_USED5_UART			AP20PERINFO(AP20_UART5, AP20PERI_NOTUSED)
                                                
#define STAR_IPC_SPI				AP20PERINFO(AP20_SPI1, NvOdmSpiPinMap_Config1)
#define STAR_NOT_USED2_SPI			AP20PERINFO(AP20_SPI2, AP20PERI_NOTUSED)       
#define STAR_NOT_USED3_SPI			AP20PERINFO(AP20_SPI3, AP20PERI_NOTUSED)  
#define STAR_NOT_USED4_SPI			AP20PERINFO(AP20_SPI4, AP20PERI_NOTUSED)  
#define STAR_NOT_USED5_SPI			AP20PERINFO(AP20_SPI5, AP20PERI_NOTUSED)  
                                                
#define STAR_I2C_PMU				AP20PERINFO(AP20_I2C_PMU, NvOdmI2cPmuPinMap_Config1) 
#define STAR_HDMI					AP20PERINFO(AP20_HDMI, NvOdmHdmiPinMap_Config1) 

#define STAR_VIBRATOR_PWM			AP20PERINFO(AP20_PWM, NvOdmPwmPinMap_Config1) 
                                                
#define STAR_AUDIO1_DAP				AP20PERINFO(AP20_DAP1, NvOdmDapPinMap_Config1)
#define STAR_AUDIO2_DAP				AP20PERINFO(AP20_DAP2, NvOdmDapPinMap_Config1) 
#define STAR_IPC_DAP				AP20PERINFO(AP20_DAP3, NvOdmDapPinMap_Config1)  
#define STAR_BT_DAP					AP20PERINFO(AP20_DAP4, NvOdmDapPinMap_Config1) 
#define STAR_FM_DAP					AP20PERINFO(AP20_DAP5, NvOdmDapPinMap_Config1) 
                                                
#define STAR_AUDIO_MCLK_EXT_CLOCK	AP20PERINFO(AP20_EXT_CLOCK1, NvOdmExternalClockPinMap_Config1)
#define STAR_AUDIO_MCLK2_EXT_CLOCK	AP20PERINFO(AP20_EXT_CLOCK2, NvOdmExternalClockPinMap_Config1)
#define STAR_CAM_MCLK_EXT_CLOCK		AP20PERINFO(AP20_EXT_CLOCK3, NvOdmExternalClockPinMap_Config1)
#define STAR_VT_VI					AP20PERINFO(AP20_VIDEO_INPUT, NvOdmVideoInputPinMap_Config2)
#define STAR_LCD_DISPLAY			AP20PERINFO(AP20_DISPLAY1, NvOdmDisplayPinMap_Config1)
#define STAR_NOT_USED_DISPLAY		AP20PERINFO(AP20_DISPLAY2, AP20PERI_NOTUSED)
#define STAR_KEY_KBD				AP20PERINFO(AP20_KBD, AP20PERI_NOTUSED)
#define STAR_TV_OUT_TVO				AP20PERINFO(AP20_TVO, NvOdmTvoPinMap_Config1) 
#define STAR_NOT_USED1_BKL_PWM		AP20PERINFO(AP20_BKL_PWM1, AP20PERI_NOTUSED)
#define STAR_NOT_USED2_BKL_PWM		AP20PERINFO(AP20_BKL_PWM2, AP20PERI_NOTUSED) 
#define STAR_NOT_USED3_BKL_PWM		AP20PERINFO(AP20_BKL_PWM3, AP20PERI_NOTUSED) 
#define STAR_NOT_USED4_BKL_PWM		AP20PERINFO(AP20_BKL_PWM4, AP20PERI_NOTUSED) 
#define STAR_NOT_USED_TWC			AP20PERINFO(AP20_TWC, AP20PERI_NOTUSED) 
#define STAR_NOT_USED_ULPI			AP20PERINFO(AP20_ULPI, AP20PERI_NOTUSED)
#define STAR_NOT_USED_SPDIF			AP20PERINFO(AP20_SPDIF, AP20PERI_NOTUSED)
#define STAR_NOT_USED_HSI			AP20PERINFO(AP20_HSI, AP20PERI_NOTUSED) 
#define STAR_NOT_USED_ATA			AP20PERINFO(AP20_ATA, AP20PERI_NOTUSED) 
#define STAR_NOT_USED_NAND			AP20PERINFO(AP20_NAND, AP20PERI_NOTUSED) 
#define STAR_NOT_USED_HDCP			AP20PERINFO(AP20_HDCP, AP20PERI_NOTUSED)
#define STAR_NOT_USED_SYNC_NOR		AP20PERINFO(AP20_SYNC_NOR, AP20PERI_NOTUSED)
#define STAR_NOT_USED_MIO			AP20PERINFO(AP20_MIO, AP20PERI_NOTUSED)
#define STAR_NOT_USED1_CRT			AP20PERINFO(AP20_CRT1, AP20PERI_NOTUSED) 
#define STAR_NOT_USED2_CRT         	AP20PERINFO(AP20_CRT2, AP20PERI_NOTUSED)
#define STAR_NOT_USED_ONEWIRE		AP20PERINFO(AP20_ONEWIRE, AP20PERI_NOTUSED) 
#define STAR_NOT_USED_PCI_EXP		AP20PERINFO(AP20_PCI_EXP, AP20PERI_NOTUSED) 
#define STAR_NOT_USED_PTM			AP20PERINFO(AP20_PTM, AP20PERI_NOTUSED) 

/* POWER INDEX SETTING */
#define VCC_CPU_1V0                 Max8907bPmuSupply_LX_V1
#define VCC_CORE_1V2                Max8907bPmuSupply_LX_V2
#define VCC_IO_1V8                  Max8907bPmuSupply_LX_V3
#define VCC_DDRx_3V3                Max8907bPmuSupply_LDO1
#define VCC_PLL_1V1                 Max8907bPmuSupply_LDO2
#define VCC_LDO3_0V                 Max8907bPmuSupply_LDO3
#define VCC_USB_3V3                 Max8907bPmuSupply_LDO4
#define VCC_eMMC_2V8_150mA          Max8907bPmuSupply_LDO5
#define VCC_HDMI_PLL_1V8            Max8907bPmuSupply_LDO6
#define VCC_SENSOR_3V0              Max8907bPmuSupply_LDO7
#define VCC_SENSOR_1V8              Max8907bPmuSupply_LDO8
#define VCC_FUSE_3V3                Max8907bPmuSupply_LDO9
#define VCC_TOUCH_3V1               Max8907bPmuSupply_LDO10
#define VCC_HDMI_3V3                Max8907bPmuSupply_LDO11
#define VCC_SDIO_3V0                Max8907bPmuSupply_LDO12
#define VCC_MOTOR_3V0               Max8907bPmuSupply_LDO13
#define VCC_GPS_2V8                 Max8907bPmuSupply_LDO14
#define VCC_APTEMP_3V3              Max8907bPmuSupply_LDO15
#define VCC_eMMC_2V8_300mA          Max8907bPmuSupply_LDO16
#define VCC_MIPI_1V2                Max8907bPmuSupply_LDO17
#define VCC_VI_1V8                  Max8907bPmuSupply_LDO18
#define VCC_LDO19_0V                Max8907bPmuSupply_LDO19
#define VCC_LDO20_0V                Max8907bPmuSupply_LDO20
#endif
#endif 
