#
# Makefile for the TDMB INC LG2102 drivers.
#

# Each configuration option enables a list of files.
# LGE
obj-$(CONFIG_LGE_BROADCAST_TDMB_LG2102)	+= src/
#obj-$(CONFIG_LGE_BROADCAST_TDMB)	+= src/
#obj-y		+= src/
