#
# Makefile for the ISDB-T MTV250 drivers.
#

# Each configuration option enables a list of files.
# LGE

obj-y		+= mtv250.o
obj-y		+= mtv250_isr.o
obj-y		+= mtv250_spi.o
obj-y		+= raontv.o
obj-y		+= raontv_rf.o
obj-y		+= raontv_isdbt.o
obj-y		+= raontv_port.o
