#
# Makefile for the TDMB LG2102 I2C drivers.
#

# Each configuration option enables a list of files.
# LGE
obj-$(CONFIG_LGE_BROADCAST)		+= broadcast_lg2102.o
obj-$(CONFIG_LGE_BROADCAST)		+= broadcast_lg2102_ioctrl.o
obj-$(CONFIG_LGE_BROADCAST)		+= LGD_FICDEC.o
obj-$(CONFIG_LGE_BROADCAST)		+= LGD_GPIO_I2C.o
obj-$(CONFIG_LGE_BROADCAST)		+= LGD_INTERFACE.o
obj-$(CONFIG_LGE_BROADCAST)		+= LGD_PROCESS.o
obj-$(CONFIG_LGE_BROADCAST)		+= LGD_QFIFO.o
obj-$(CONFIG_LGE_BROADCAST)		+= LGD_RF_CTRL500.o
obj-$(CONFIG_LGE_BROADCAST)		+= LGD_DAB_DLS.o
obj-$(CONFIG_LGE_BROADCAST)		+= LGD_EWSDEC.o
#obj-y		+= broadcast_lg2102.o
#obj-y		+= broadcast_lg2102_ioctrl.o
#obj-y		+= LGD_FICDEC.o
#obj-y		+= LGD_GPIO_I2C.o
#obj-y		+= LGD_INTERFACE.o
#obj-y		+= LGD_PROCESS.o
#obj-y		+= LGD_QFIFO.o
#obj-y		+= LGD_RF_CTRL500.o
#obj-y		+= LGD_DAB_DLS.o
#obj-y		+= LGD_EWSDEC.o

