#
# Makefile for the TDMB LG2102 I2C drivers.
#

# Each configuration option enables a list of files.
# LGE
obj-$(CONFIG_LGE_BROADCAST_TDMB_LG2102)		+= broadcast_lg2102_drv_if.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_LG2102)		+= broadcast_lg2102.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_LG2102)		+= tdmb_tunerbbdrv_lg2102.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_LG2102)		+= INC_INTERFACE.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_LG2102)		+= INC_PROCESS.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_LG2102)		+= INC_FICDEC.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_LG2102)		+= INC_QFIFO.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_LG2102)		+= INC_RF_CTRL500.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_LG2102)		+= INC_GPIO_I2C.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_LG2102)		+= INC_DAB_DLS.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_LG2102)		+= INC_EWSDEC.o

#obj-y		+= broadcast_lg2102.o
#obj-y		+= broadcast_lg2102_drv_if.o
#obj-y		+= tdmb_tunerbbdrv_lg2102.o
#obj-y		+= INC_INTERFACE.o
#obj-y		+= INC_PROCESS.o
#obj-y		+= INC_FICDEC.o
#obj-y		+= INC_QFIFO.o
#obj-y		+= INC_RF_CTRL500.o
#obj-y		+= INC_DAB_DLS.o
#obj-y		+= INC_GPIO_I2C.o
#obj-y		+= INC_EWSDEC.o
