#LGE_KERNEL_MUX START
EXTRA_CFLAGS += -DLGE_KERNEL_MUX

#ifneq (, $(filter su880 ku8800 , $(TARGET_MODEL)))
#obj-y += ifx_ts0710_mux.o 
#obj-y += ts0710_mux.o 
#else
obj-y += ts0710_mux.o 
#endif

#LGE_KERNEL_MUX END

