#
# Makefile for the TDMB T3900 drivers.
#

# Each configuration option enables a list of files.
# LGE
#obj-$(CONFIG_LGE_BROADCAST)		+= broadcast_t3900_drv_if.o
#obj-$(CONFIG_LGE_BROADCAST)		+= broadcast_t3900.o
#obj-$(CONFIG_LGE_BROADCAST)		+= tdmb_tunerbbdrv_t3900.o
#obj-$(CONFIG_LGE_BROADCAST)		+= INC_INTERFACE.o
#obj-$(CONFIG_LGE_BROADCAST)		+= INC_PROCESS.o
#obj-$(CONFIG_LGE_BROADCAST)		+= INC_FICDEC.o
#obj-$(CONFIG_LGE_BROADCAST)		+= INC_QFIFO.o
#obj-$(CONFIG_LGE_BROADCAST)		+= INC_RF_CTRL500.o

obj-y		+= broadcast_t3900_drv_if.o
obj-y		+= broadcast_t3900.o
obj-y		+= tdmb_tunerbbdrv_t3900.o
obj-y		+= INC_INTERFACE.o
obj-y		+= INC_PROCESS.o
obj-y		+= INC_FICDEC.o
obj-y		+= INC_QFIFO.o
obj-y		+= INC_RF_CTRL500.o