obj-${CONFIG_MACH_BSSQ}             		+= board-bssq.o
obj-${CONFIG_MACH_BSSQ}             		+= board-bssq-audio.o
obj-${CONFIG_MACH_BSSQ}             		+= board-bssq-emc.o
ifeq ($(CONFIG_LU6500),y)
obj-${CONFIG_MACH_BSSQ}             		+= board-bssq-kbc.o
endif
obj-${CONFIG_MACH_BSSQ}             		+= board-bssq-panel.o
obj-${CONFIG_MACH_BSSQ}             		+= board-bssq-pinmux.o
obj-${CONFIG_MACH_BSSQ}             		+= board-bssq-power.o
obj-${CONFIG_MACH_BSSQ}             		+= board-bssq-sdhci.o
obj-${CONFIG_MACH_BSSQ}             		+= board-bssq-bt.o
obj-$(CONFIG_BSSQ_REBOOT_MONITOR)		+= board-bssq-reboot.o
obj-${CONFIG_MACH_BSSQ}                     += board-bssq-nv.o
