obj-$(CONFIG_INPUT_TEGRA_ODM_ACCEL)	+= accelerometer/
obj-$(CONFIG_INPUT_TEGRA_ODM_SCROLL)	+= scrollwheel/
obj-$(CONFIG_KEYBOARD_TEGRA_NVEC)	+= keyboard/
obj-$(CONFIG_TOUCHSCREEN_TEGRA_ODM)	+= touch/
obj-$(CONFIG_TEGRA_ODM_VIBRATE)		+= vibrate/
obj-$(CONFIG_MOUSE_TEGRA_NVEC)		+= mouse/
obj-$(CONFIG_TEGRA_BATTERY_NVEC)	+= battery/
obj-$(CONFIG_BATTERY_TEGRA_ODM)		+= battery/
