
	{TEGRA_PINGROUP_ATA,   TEGRA_MUX_IDE,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// NC
	{TEGRA_PINGROUP_ATB,   TEGRA_MUX_SDIO4,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// microsd det, mmc clk, mmc cmd
	{TEGRA_PINGROUP_ATC,   TEGRA_MUX_GMI,			TEGRA_PUPD_PULL_UP,		TEGRA_TRI_NORMAL},		// gpio
	{TEGRA_PINGROUP_ATD,   TEGRA_MUX_GMI,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// NC
	{TEGRA_PINGROUP_ATE,   TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// NC, pull dn(strapping)
	{TEGRA_PINGROUP_CDEV1, TEGRA_MUX_PLLA_OUT,		TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// audio mclk2(set dynamically)
	{TEGRA_PINGROUP_CDEV2, TEGRA_MUX_PLLP_OUT4,		TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// audio mclk(set dynamically)
	{TEGRA_PINGROUP_CRTP,  TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// NC
	{TEGRA_PINGROUP_CSUS,  TEGRA_MUX_VI_SENSOR_CLK, TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// CAM_MCLK
	{TEGRA_PINGROUP_DAP1,  TEGRA_MUX_DAP1,          TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// dap1
	{TEGRA_PINGROUP_DAP2,  TEGRA_MUX_DAP2,          TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// dap2
	{TEGRA_PINGROUP_DAP3,  TEGRA_MUX_DAP3,          TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// dap3
	{TEGRA_PINGROUP_DAP4,  TEGRA_MUX_DAP4,          TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// dap4
	{TEGRA_PINGROUP_DDC,   TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// NC
	{TEGRA_PINGROUP_DTA,   TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// 8M CAM VCM en, VT CAM pwdn
	{TEGRA_PINGROUP_DTB,   TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// flash LED
	{TEGRA_PINGROUP_DTC,   TEGRA_MUX_VI,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// VT hsync, vsync
	{TEGRA_PINGROUP_DTD,   TEGRA_MUX_VI,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// VT pclk
	{TEGRA_PINGROUP_DTE,   TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// VT/8M reset n, flash en
#ifdef USE_GEN3_I2C_GPIO
	{TEGRA_PINGROUP_DTF,   TEGRA_MUX_NONE,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// CAM I2C
#else
	{TEGRA_PINGROUP_DTF,   TEGRA_MUX_I2C3,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// CAM I2C
#endif
	{TEGRA_PINGROUP_GMA,   TEGRA_MUX_SDIO4,			TEGRA_PUPD_PULL_UP, 	TEGRA_TRI_NORMAL},		// mmc dat[0..3]
	{TEGRA_PINGROUP_GMB,   TEGRA_MUX_GMI,			TEGRA_PUPD_PULL_DOWN,	TEGRA_TRI_TRISTATE},		// BT host wake up
	{TEGRA_PINGROUP_GMC,   TEGRA_MUX_UARTD,			TEGRA_PUPD_PULL_UP, 	TEGRA_TRI_NORMAL},		//  HOOK det
	{TEGRA_PINGROUP_GMD,   TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// NC
	{TEGRA_PINGROUP_GME,   TEGRA_MUX_SDIO4, 		TEGRA_PUPD_PULL_UP, 	TEGRA_TRI_NORMAL},		// mmc dat[4..7]
	{TEGRA_PINGROUP_GPU,   TEGRA_MUX_PWM,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// muic int, uart sw, vib pwm, vib en, ipc srdy
	{TEGRA_PINGROUP_GPU7,  TEGRA_MUX_RTCK,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// jtag rtck
	{TEGRA_PINGROUP_GPV,   TEGRA_MUX_PCIE,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// NC
	{TEGRA_PINGROUP_HDINT, TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// gauge int
	{TEGRA_PINGROUP_I2CP,  TEGRA_MUX_I2C,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		//  power i2c sda, slc
	{TEGRA_PINGROUP_IRRX,  TEGRA_MUX_GMI,			TEGRA_PUPD_PULL_DOWN,		TEGRA_TRI_NORMAL},		// ipc mrdy1 
	{TEGRA_PINGROUP_IRTX,  TEGRA_MUX_GMI,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// NC
	{TEGRA_PINGROUP_KBCA,  TEGRA_MUX_KBC,			TEGRA_PUPD_PULL_UP, 	TEGRA_TRI_NORMAL},		// KEYBOARD
	{TEGRA_PINGROUP_KBCB,  TEGRA_MUX_KBC,			TEGRA_PUPD_PULL_UP, 	TEGRA_TRI_NORMAL},		// CHG_EN_SET_N_AP20,CHG_STATUS_N_AP20,WLAN_HOST_WAKEUP
	{TEGRA_PINGROUP_KBCC,  TEGRA_MUX_KBC,			TEGRA_PUPD_PULL_UP, 	TEGRA_TRI_NORMAL},		// KEYBOARD
	{TEGRA_PINGROUP_KBCD,  TEGRA_MUX_KBC,			TEGRA_PUPD_PULL_UP, 	TEGRA_TRI_NORMAL},		// KEYBOARD
	{TEGRA_PINGROUP_KBCE,  TEGRA_MUX_KBC,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// ??
	{TEGRA_PINGROUP_KBCF,  TEGRA_MUX_KBC,			TEGRA_PUPD_PULL_UP, 	TEGRA_TRI_NORMAL},		// KEYBOARD
	{TEGRA_PINGROUP_LCSN,  TEGRA_MUX_DISPLAYA,		TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// lcd cs
	{TEGRA_PINGROUP_LD9,   TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL, 	TEGRA_TRI_NORMAL},		// mdm usb vbus en
	{TEGRA_PINGROUP_LD0,   TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// NC
	{TEGRA_PINGROUP_LD1,   TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// gen2 i2c switch
	{TEGRA_PINGROUP_LD10,  TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// lp8720(CAM PMIC)en/1seg 1.2v en
	{TEGRA_PINGROUP_LD11,  TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// DMB en/1seg en
	{TEGRA_PINGROUP_LD12,  TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// motion int
	{TEGRA_PINGROUP_LD13,  TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// bd2802(key led) reset for LU6500 Rev.E
	{TEGRA_PINGROUP_LD14,  TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// NC
	{TEGRA_PINGROUP_LD15,  TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// WM ldo en
	{TEGRA_PINGROUP_LD16,  TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// NC
	{TEGRA_PINGROUP_LD17,  TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// NC
	{TEGRA_PINGROUP_LD2,   TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// audio_int_n
	{TEGRA_PINGROUP_LD3,   TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// bd6084(lcd cp) en(resetb)
	{TEGRA_PINGROUP_LD4,   TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// X2 DMB_RESET
	{TEGRA_PINGROUP_LD5,   TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// X2 DMB_INT
	{TEGRA_PINGROUP_LD6,   TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// X2 DMB_EN, bd2802(key led) reset
	{TEGRA_PINGROUP_LD7,   TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// NC
	{TEGRA_PINGROUP_LD8,   TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// com_int
	{TEGRA_PINGROUP_LDC,   TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// NC
	{TEGRA_PINGROUP_LDI,   TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// NC
	{TEGRA_PINGROUP_LHP0,  TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// NC
	{TEGRA_PINGROUP_LHP1,  TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// BT en
	{TEGRA_PINGROUP_LHP2,  TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// wlan_en
	{TEGRA_PINGROUP_LHS,   TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// bl_dcdc scl
	{TEGRA_PINGROUP_LM0,   TEGRA_MUX_SPI3,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// DMB/1seg spi3 cs
	{TEGRA_PINGROUP_LM1,   TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// NC
	{TEGRA_PINGROUP_LPP,   TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// NC
	{TEGRA_PINGROUP_LPW0,  TEGRA_MUX_SPI3,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// DMB/1seg spi3 sdi
	{TEGRA_PINGROUP_LPW1,  TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// CHG PGB N/NC
	{TEGRA_PINGROUP_LPW2,  TEGRA_MUX_SPI3,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// DMB spi3 sdo
	{TEGRA_PINGROUP_LSC0,  TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// GYRO_INT
	{TEGRA_PINGROUP_LSC1,  TEGRA_MUX_SPI3,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// DBM spi3 clk
	{TEGRA_PINGROUP_LSCK,  TEGRA_MUX_DISPLAYA,		TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// NC
	{TEGRA_PINGROUP_LSDA,  TEGRA_MUX_DISPLAYA,		TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// NC
	{TEGRA_PINGROUP_LSDI,  TEGRA_MUX_DISPLAYA,		TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// NC
#ifndef CONFIG_TEGRA_DSI
	{TEGRA_PINGROUP_LSPI,  TEGRA_MUX_DISPLAYA,		TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LVP0,  TEGRA_MUX_DISPLAYA,		TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},              // lcd reset
#else
	{TEGRA_PINGROUP_LSPI,  TEGRA_MUX_DISPLAYA,		TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// lcd_te
	{TEGRA_PINGROUP_LVP0,  TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// lcd reset
#endif
	{TEGRA_PINGROUP_LVP1,  TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// lcd_maker_id
	// 20110517 hyokmin.kwon@lge.com To set pull up to spi3_cs for 1seg, only this pinmux called last is changed
	{TEGRA_PINGROUP_LVS,   TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL, 	TEGRA_TRI_NORMAL},		// bl_dcdc_sda
	{TEGRA_PINGROUP_OWC,   TEGRA_MUX_OWR,			TEGRA_PUPD_PULL_UP, 	TEGRA_TRI_TRISTATE},		// test point
	{TEGRA_PINGROUP_PMC,   TEGRA_MUX_PWR_ON,		TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// power
	{TEGRA_PINGROUP_PTA,   TEGRA_MUX_I2C2,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// audio gen2 i2c scl, sda
	{TEGRA_PINGROUP_RM,    TEGRA_MUX_I2C,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// touch gen1 i2c scl, sda
	{TEGRA_PINGROUP_SDB,   TEGRA_MUX_SDIO3, 		TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// micro sd
	{TEGRA_PINGROUP_SDC,   TEGRA_MUX_SDIO3, 		TEGRA_PUPD_NORMAL, 	TEGRA_TRI_NORMAL},		// micro sd
	{TEGRA_PINGROUP_SDD,   TEGRA_MUX_SDIO3, 		TEGRA_PUPD_NORMAL, 	TEGRA_TRI_NORMAL},		// micro sd
	{TEGRA_PINGROUP_SDIO1, TEGRA_MUX_SDIO1, 		TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// wlan
	{TEGRA_PINGROUP_SLXA,  TEGRA_MUX_SDIO3, 		TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// NC
	{TEGRA_PINGROUP_SLXC,  TEGRA_MUX_SDIO3, 		TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// NC
	{TEGRA_PINGROUP_SLXD,  TEGRA_MUX_SDIO3, 		TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// NC
	{TEGRA_PINGROUP_SLXK,  TEGRA_MUX_SDIO3, 		TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// micro sd
	{TEGRA_PINGROUP_SPDI,  TEGRA_MUX_RSVD, 			TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// NC
	{TEGRA_PINGROUP_SPDO,  TEGRA_MUX_RSVD, 			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// hdmi_reg_en
	{TEGRA_PINGROUP_SPIA,  TEGRA_MUX_GMI,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// spi2_ipc_mosi (NU)
	{TEGRA_PINGROUP_SPIB,  TEGRA_MUX_GMI,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// spi2_ipc_miso (NU)
	{TEGRA_PINGROUP_SPIC,  TEGRA_MUX_GMI,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// spi2 ipc
	{TEGRA_PINGROUP_SPID,  TEGRA_MUX_GMI,			TEGRA_PUPD_NORMAL, 	TEGRA_TRI_NORMAL},		// bt_wake_up_n
	{TEGRA_PINGROUP_SPIE,  TEGRA_MUX_GMI,			TEGRA_PUPD_NORMAL, 	TEGRA_TRI_TRISTATE},		// prox_out, touch_int_n
	{TEGRA_PINGROUP_SPIF,  TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// ear_bias_en
	{TEGRA_PINGROUP_SPIG,  TEGRA_MUX_SPI2_ALT,		TEGRA_PUPD_NORMAL,		TEGRA_TRI_TRISTATE},		// charger_irqb
	{TEGRA_PINGROUP_SPIH,  TEGRA_MUX_SPI2_ALT,		TEGRA_PUPD_PULL_UP, 	TEGRA_TRI_TRISTATE},		// batt_low_int_n
	{TEGRA_PINGROUP_UAA,   TEGRA_MUX_UARTA, 		TEGRA_PUPD_PULL_UP, 	TEGRA_TRI_NORMAL},		// ipc rx,tx,cts,rtx uart1
	{TEGRA_PINGROUP_UAB,   TEGRA_MUX_UARTA,			TEGRA_PUPD_PULL_DOWN,		TEGRA_TRI_NORMAL},	// ipc srdy2, DMB int, DMB reset, ipc mrdy2
	{TEGRA_PINGROUP_UAC,   TEGRA_MUX_RSVD,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},  	// mdm resest, mdm pwer on, ap pwr on, mdm reset flag
	{TEGRA_PINGROUP_UAD,   TEGRA_MUX_IRDA,			TEGRA_PUPD_PULL_UP, 	TEGRA_TRI_NORMAL},		// uart2_tx_rx_ap20
	{TEGRA_PINGROUP_UCA,   TEGRA_MUX_UARTC, 		TEGRA_PUPD_PULL_UP, 	TEGRA_TRI_NORMAL},		// bt_uart
	{TEGRA_PINGROUP_UCB,   TEGRA_MUX_UARTC, 		TEGRA_PUPD_PULL_UP, 	TEGRA_TRI_NORMAL},		// bt_uart
	{TEGRA_PINGROUP_UDA,   TEGRA_MUX_SPI1,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},		// spi1_ipc
	{TEGRA_PINGROUP_CK32,  TEGRA_MUX_NONE,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_DDRC,  TEGRA_MUX_NONE,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_PMCA,  TEGRA_MUX_NONE,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_PMCB,  TEGRA_MUX_NONE,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_PMCC,  TEGRA_MUX_NONE,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_PMCD,  TEGRA_MUX_NONE,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_PMCE,  TEGRA_MUX_NONE,			TEGRA_PUPD_PULL_UP, 	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_XM2C,  TEGRA_MUX_NONE,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_XM2D,  TEGRA_MUX_NONE,			TEGRA_PUPD_NORMAL,		TEGRA_TRI_NORMAL},

