#LGE_CHANGE  yongkyun.lee@ lge.com 
#obj-$(CONFIG_MAX14526)			+= max14526.o
obj-$(CONFIG_MAX14526)			+= muic.o
obj-$(CONFIG_MAX14526)			+= muic_maxim.o
obj-$(CONFIG_MAX14526)			+= muic_ti.o
#MOBII_CHNANGE_S 20120416 jd.park@mobii.co.kr : FOTA UA Upgrade for ICS
obj-$(CONFIG_MAX14526)			+= fota.o
#MOBII_CHNANGE_E 20120416 jd.park@mobii.co.kr : FOTA UA Upgrade for ICS